package net.net63.codearcade.LSD.screens;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.scenes.scene2d.Event;
import com.badlogic.gdx.scenes.scene2d.EventListener;
import com.badlogic.gdx.scenes.scene2d.InputEvent;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import net.net63.codearcade.LSD.LSD;
import net.net63.codearcade.LSD.screens.overlays.GameOverScreen;
import net.net63.codearcade.LSD.screens.overlays.LevelCompleteScreen;
import net.net63.codearcade.LSD.utils.CentreGUI;
import net.net63.codearcade.LSD.utils.Constants;
import net.net63.codearcade.LSD.utils.GUIBuilder;
import net.net63.codearcade.LSD.utils.LevelManager;
import net.net63.codearcade.LSD.world.GameWorld;

/**
 * The main game screen class that represents the state when the
 * game is being played
 * 
 * @author Basim
 *
 */
public class GameScreen extends AbstractScreen implements EventListener {

    private CentreGUI centreGUI;
    private GameWorld gameWorld;

    private Label scoreLabel;

    private int levelId;
    private boolean logicPaused = false;

	public GameScreen(LSD game, int levelId) {
		super(game);

        this.levelId = levelId;

        //Create a new world with the map at the current level
        gameWorld = new GameWorld(LevelManager.getLevel(Constants.DEFAULT_PACK, levelId));
        setupUI();
	}

    @Override
    public void pauseLogic() {
        if (!logicPaused) gameWorld.pauseLogic();
        logicPaused = true;
    }

    @Override
    public void resumeLogic() {
        if (logicPaused) gameWorld.resumeLogic();
        logicPaused = false;
    }

    /**
     * The level that is being played by this state
     *
      * @return The current level
     */
    public int getLevelId() { return levelId; }

    private void setupUI() {
        //Create and position the score the label at the top centre
        scoreLabel = GUIBuilder.createLabel("", 50, Color.YELLOW);
        scoreLabel.setPosition((800 - scoreLabel.getWidth()) / 2.0f , 550 - scoreLabel.getHeight());

        //Create the GUI manager and add listeners
        centreGUI = new CentreGUI();
        centreGUI.getStage().addActor(scoreLabel);
        centreGUI.getStage().addListener(this);
    }

	@Override
	public void resize(int width, int height) {
		super.resize(width, height);

        //Update the gui viewport and the game world
        gameWorld.resize(width, height);
		centreGUI.resize(width, height);
	}

    @Override
    public void show() { if (logicPaused) resumeLogic(); }

    @Override
    public void hide() { pauseLogic(); }

	@Override
	public void render(float delta) {
		super.render(delta);

        //Render/complete the logic and update UI elements to show it
        gameWorld.update(delta);
        updateScore();

        //Handle user events and render the GUI
        centreGUI.render(delta);

        //Check if the game is finished
        if (!logicPaused && gameWorld.isGameOver()) {
            pauseLogic();

            //Either level over or level completed
            if (gameWorld.isGameWon()) game.setScreen(new LevelCompleteScreen(game, this));
            else game.setScreen(new GameOverScreen(game, this));
        }
	}

    @Override
    public void dispose() {
        super.dispose();

        //Dispose assets from members
        gameWorld.dispose();
        centreGUI.dispose();
    }

    private void updateScore() {
        scoreLabel.setText(gameWorld.getScore());
    }


    @Override
    public boolean handle(Event event) {

        //Handle events generated by the stage
        if (!logicPaused && event instanceof InputEvent) {
            InputEvent inputEvent = (InputEvent) event;

            switch (inputEvent.getType()) {

                //Aim the player to where the user has aimed it to
                case touchDown: case touchDragged:
                    gameWorld.aimPlayer(Gdx.input.getX(), Gdx.input.getY());
                    break;

                //Once the touch is released then fire the player
                case touchUp:
                    gameWorld.launchPlayer();
                    break;

                //Don't handle any other event
                default:
                    return false;
            }

            return true;
        }

        return false;
    }
}
