package net.net63.codearcade.LSD.utils;

/**
 * Class to hold the settings (mutable) for the game for
 * the curren user
 * 
 * @author Basim
 *
 */
public class Settings {

    private static int currentLevel = 0;
    private static float musicVolume = 1f;
    private static float soundVolume = 1f;


    /**
    * Load all the default values for the settings, this is automatically
    * called if there is an error reading the file
    */
    public static void loadDefaults() {
        currentLevel = 0;
        musicVolume = 1f;
        soundVolume = 1f;
    }

	/**
	 * Load all the parameters in the settings from a String generated by this class
	 * 
	 * @param loadString The String to load the settings from (as generated by saveSettings)
	 */
	public static void loadSettings(String loadString) {

	}
	
	/**
	 * Returns all the parameters of this class in an easy to store String
	 * 
	 * @return The parameters in String format
	 */
	public static String saveSettings() {

        return "";
	}

    /* ---------------------- Getters & Setters -----------------------------*/

    public static int getCurrentLevel() {
        return currentLevel;
    }

    public static void setCurrentLevel(int newLevel) {
        currentLevel = newLevel;
    }

    public static float getMusicVolume() {
        return musicVolume;
    }

    public static void setMusicVolume(float musicVolume) {
        Settings.musicVolume = musicVolume;
    }

    public static float getSoundVolume() {
        return soundVolume;
    }

    public static void setSoundVolume(float soundVolume) {
        Settings.soundVolume = soundVolume;
    }


}
