package net.net63.codearcade.LSD.utils;

/**
 * Class to hold the settings (mutable) for the game for
 * the curren user
 * 
 * @author Basim
 *
 */
public class Settings {
	
	/**
	 * 
	 * 
	 * @param loadString The String to load the settings from (as generated by saveSettings)
	 */
	public static void loadSettings(String loadString) {
		
	}
	
	public static String saveSettings() {
		return "";
	}
	
	
}
